# Clave única del proyecto en SonarCloud
sonar.projectKey=FMAT-Restaurant_Auth-Backend
sonar.organization=fmat-restaurant

# Nombre descriptivo del microservicio
sonar.projectName=Auth-Backend
sonar.projectVersion=1.0

# Rutas de código fuente y pruebas
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.spec.ts
sonar.exclusions=src/**/*.spec.ts,dist/**,node_modules/**,coverage/**

# Configuración de TypeScript y Cobertura (LCOV)
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.qualitygate.wait=true
